### ISSUE TITLE
Badge does not match score

### ISSUE THREAD

**Issue by michelpmcdonald** [gojp/goreportcard#290]
Hi,
My score is 100% but the badge is stuck on B:

https://goreportcard.com/report/github.com/michelpmcdonald/go-peat

I did create and completely destroy the repo a few times in git hub using the exact same repo name, not sure if that matters...

thanks

**Comment by shawnps** [comment]
@michelpmcdonald thanks for bringing this to our attention - there was a bug in some caching code we're testing on the server. It should be fixed now, could you take another look?

**Comment by michelpmcdonald** [comment]
Looks good on goreportcard.com, still shows as B score on github, but guessing that's nothing to do with goreportcard.

thank you
