### ISSUE TITLE
Repository with `main` branch is not updated

### ISSUE THREAD

**Issue by alimoli** [gojp/goreportcard#357]
My [repository](https://github.com/limoli/kid) report is not refreshed correctly.
The branch is `main`.

Clicking on one of the files links present on the report I am redirected to Github, but Github says:
![Screenshot 2021-10-06 at 13 35 06](https://user-images.githubusercontent.com/68189985/136195003-6df797e1-5bd1-4570-8eed-774c1b0bbf82.png)

Indeed all the links to the files in the report use the `master` branch instead for `main`.

**Comment by TheDiveO** [comment]
ˋmasterˋ branch repositories seem to be affected, too. Refresh fails. Sadly, goreportcard seems to degenerate...

**Comment by shawnps** [comment]
@TheDiveO please try again, we just deployed a fix.

**Comment by TheDiveO** [comment]
Yes, that fixed the refresh problem for my repository/ies. Thank you!

**Comment by synfinatic** [comment]
Seems to be still a problem for me?  https://goreportcard.com/report/github.com/synfinatic/aws-sso-cli

**Comment by shawnps** [comment]
@synfinatic we're experimenting with using https://proxy.golang.org for downloading modules. The latest version we get from there is v1.2.3:

https://proxy.golang.org/github.com/synfinatic/aws-sso-cli/@latest

We still need to do some UI work to display what version of the module we checked.

**Comment by synfinatic** [comment]
Ah, that would explain it!  And yes, indicating what version you're analyzing would be helpful.  I was expecting you would be pulling HEAD from `main`/default branch.

**Comment by shawnps** [comment]
@synfinatic module version is displayed on the page now 👍  https://goreportcard.com/report/github.com/synfinatic/aws-sso-cli

**Comment by shawnps** [comment]
@alimoli the GitHub links now point to the latest module version. For example https://github.com/limoli/kid/blob/v1.0.0/common.go#L1.
